apiVersion: v1
kind: Namespace
metadata:
  name: metal3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal3-baremetal-operator
  namespace: metal3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: metal3-baremetal-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - watch
  - list
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal3-baremetal-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal3-baremetal-operator
subjects:
- kind: ServiceAccount
  name: metal3-baremetal-operator
  namespace: metal3
- kind: User
  name: developer
---
apiVersion: v1
data:
  CACHEURL: http://172.22.0.1/images
  DEPLOY_KERNEL_URL: http://172.22.0.2:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://172.22.0.2:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 172.22.0.10,172.22.0.100
  HTTP_PORT: "6180"
  IRONIC_ENDPOINT: http://172.22.0.2:6385/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_ENDPOINT: http://172.22.0.2:5050/v1/
  PROVISIONING_INTERFACE: eth2
kind: ConfigMap
metadata:
  name: ironic-bmo-configmap-mgdd5c7hck
  namespace: metal3
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: mariadb-password-d88m524c46
  namespace: metal3
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
  namespace: metal3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metal3-baremetal-operator
  template:
    metadata:
      labels:
        name: metal3-baremetal-operator
    spec:
      containers:
      - command:
        - /baremetal-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: baremetal-operator
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/baremetal-operator
        imagePullPolicy: Always
        name: baremetal-operator
        ports:
        - containerPort: 60000
          name: metrics
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        name: ironic-dnsmasq
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runmariadb
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-d88m524c46
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        name: mariadb
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        name: ironic-httpd
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-d88m524c46
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        name: ironic
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/ironic-inspector
        imagePullPolicy: Always
        name: ironic-inspector
        securityContext:
          privileged: true
      hostNetwork: true
      initContainers:
      - command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-mgdd5c7hck
        image: quay.io/metal3-io/ironic-ipa-downloader
        imagePullPolicy: Always
        name: ironic-ipa-downloader
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      serviceAccountName: metal3-baremetal-operator
      volumes:
      - emptyDir: {}
        name: ironic-data-volume
