apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: cabpk-controller-manager
  name: cabpk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cabpk-leader-election-role
  namespace: cabpk-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cabpk-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigs
  - kubeadmconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cabpk-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cabpk-leader-election-rolebinding
  namespace: cabpk-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cabpk-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cabpk-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpk-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cabpk-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpk-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpk-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: cabpk-controller-manager
  name: cabpk-controller-manager-metrics-service
  namespace: cabpk-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: cabpk-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: cabpk-controller-manager
  name: cabpk-controller-manager
  namespace: cabpk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: cabpk-controller-manager
  template:
    metadata:
      labels:
        control-plane: cabpk-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --v=4
        - --enable-leader-election
        image: gcr.io/k8s-staging-capi-kubeadm/cluster-api-kubeadm-controller:latest
        imagePullPolicy: Always
        name: manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
