apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: capbm-controller-manager
    controller-tools.k8s.io: "1.0"
  name: capbm-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-leader-election-role
  namespace: capbm-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    control-plane: capbm-controller-manager
  name: capbm-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - baremetalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - baremetalclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - baremetalmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - baremetalmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-leader-election-rolebinding
  namespace: capbm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capbm-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capbm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capbm-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capbm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capbm-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capbm-system
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-webhook-server-secret
  namespace: capbm-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: capbm-controller-manager
    controller-tools.k8s.io: "1.0"
  name: capbm-controller-manager-service
  namespace: capbm-system
spec:
  ports:
  - port: 443
  selector:
    control-plane: capbm-controller-manager
    controller-tools.k8s.io: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: capbm-controller-manager
  name: capbm-controller-metrics-service
  namespace: capbm-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: capbm-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: capbm-controller-manager
    controller-tools.k8s.io: "1.0"
  name: capbm-controller-manager
  namespace: capbm-system
spec:
  selector:
    matchLabels:
      control-plane: capbm-controller-manager
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: capbm-controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: $(WEBHOOK_SECRET_NAME)
        image: quay.io/metal3-io/cluster-api-provider-baremetal:v1alpha2
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capbm-webhook-server-secret
